services:
    php:
        build:
            context: ./docker/php
            target: base
        image: speech2text-php
        volumes:
            - ./:/app
        command: [ 'composer', 'install' ]

    api:
        image: speech2text-php
        depends_on:
            - php
            - vite
            - redis
            - pgsql
        restart: on-failure
        volumes:
            - ./:/app
        ports:
            - '8000:8000'
        healthcheck:
            test: [ "CMD", "curl", "-f", "${APP_URL}/status" ]
            retries: 6
            timeout: 5s
        entrypoint: [ 'php', 'artisan', 'serve', '--host=0.0.0.0', '--port=8000' ]

    schedule:
        image: speech2text-php
        depends_on:
            - php
            - redis
            - pgsql
        restart: on-failure
        volumes:
            - ./:/app
        entrypoint: [ 'php', 'artisan', 'schedule:work' ]

    horizon:
        image: speech2text-php
        depends_on:
            - php
            - redis
            - pgsql
        restart: on-failure
        volumes:
            - ./:/app
        entrypoint: [ 'php', 'artisan', 'horizon' ]

    node:
        build: ./docker/node
        image: speech2text-node
        volumes:
            - ./:/app
        command: [ 'npm', 'install' ]

    vite:
        depends_on:
            - node
        image: speech2text-node
        volumes:
            - ./:/app
        restart: on-failure
        entrypoint: [ 'npm', 'run', 'build' ]

    redis:
        build: ./docker/redis
        image: speech2text-redis
        restart: on-failure
        volumes:
            - 'redis-data:/data'
        entrypoint: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"

    pgsql:
        build: ./docker/pgsql
        image: speech2text-pgsql
        restart: on-failure
        environment:
            PGPASSWORD: 'secret'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'pgsql-data:/var/lib/postgresql/data'
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 6
            timeout: 5s

volumes:
    pgsql-data:
    redis-data:
